import streamlit as st

st.title("📋 Terms of Service")
st.caption("Last updated: 2026-05-21")

st.markdown("""
## 1. Acceptance

By using InterviewForge ("the Service"), you agree to these Terms of Service. If you do not
agree, do not use the Service.

---

## 2. Eligibility

You must be **18 years or older** to use this Service. By creating an account, you confirm
that you meet this requirement.

---

## 3. Permitted Use

InterviewForge is provided for **personal interview preparation only**. You may:

- Practice mock interviews for your own job applications
- Download and keep your evaluation reports for personal use
- Share individual report links with others (e.g., a mentor or recruiter)

---

## 4. Prohibited Use

You must **not**:

- Use the Service for commercial purposes without prior written consent
- Scrape, crawl, or programmatically access the Service beyond normal use
- Attempt to reverse-engineer, bypass security controls, or access other users' data
- Use the Service to train machine learning models or build competing products
- Submit content that violates applicable law (harmful, illegal, or abusive material)
- Attempt prompt injection, jailbreaking, or manipulation of the AI systems

Violations may result in immediate account termination and, where appropriate, legal action.

---

## 5. Intellectual Property

- **Your content:** Interview answers and job descriptions you submit remain yours.
- **Our content:** The Service, its design, prompts, and evaluation logic are owned by the
  Service operator. You may not reproduce or distribute them.
- **AI outputs:** Evaluation reports are generated by AI and provided for informational
  purposes only. They do not constitute professional career advice.

---

## 6. Disclaimer of Warranties

THE SERVICE IS PROVIDED "AS IS" FOR EDUCATIONAL AND PRACTICE PURPOSES. WE MAKE NO WARRANTIES,
EXPRESS OR IMPLIED, REGARDING THE ACCURACY, COMPLETENESS, OR FITNESS FOR A PARTICULAR PURPOSE
OF ANY AI-GENERATED CONTENT. Interview performance in the Service does not guarantee outcomes
in real interviews.

---

## 7. Limitation of Liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE OPERATOR SHALL NOT BE LIABLE FOR ANY
INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE,
INCLUDING BUT NOT LIMITED TO LOSS OF EMPLOYMENT OPPORTUNITIES.

---

## 8. Governing Law and Jurisdiction

These Terms are governed by the laws of the **Federal Republic of Germany**. Any disputes
shall be subject to the exclusive jurisdiction of the courts of **Berlin, Germany**.

---

## 9. Changes to Terms

We may update these Terms at any time. Continued use of the Service after changes are posted
constitutes acceptance of the updated Terms. Material changes will be communicated via email
to registered users.

---

## 10. Contact

For questions about these Terms, contact us via the email listed on the Privacy Policy page.
""")
