[theme]
primaryColor = "#10b981"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f4f5"
textColor = "#18181b"
font = "sans serif"

[server]
maxUploadSize = 5
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
